Repository OWN-SIZE/onsize-website, pull requests merged in 2023-02, with the labels that each got.

#89 chore/#85: 로그인 api 요청 client > axiosBasic 수정, 쿠키 set 코드 위치 변경
  apis/index.tsx
  apis/user.ts
Labels: FIX

#94 fix: 마이사이즈 placeholder value 로 바꾸기 및 저장하기 api 연결
  components/common/SizeForm/SizeForm.tsx
  components/common/SizeForm/SizeInput.tsx
  components/common/ThumbNail/ThumbNail.tsx
  components/common/modal/CategoryCreateModal.tsx
  components/mysize/Mysize.tsx
  hooks/queries/category.ts
  hooks/queries/mySize.ts
  pages/category/index.tsx
Labels: FIX, FEAT

#114 recoil-persist 적용 및 alert 무한반복 이슈 해결
  apis/index.tsx
  hooks/queries/auth.ts
  package-lock.json
  package.json
  states/user.ts
Labels: FIX

#128 탈퇴, 로그아웃 구현
  apis/user.ts
  assets/img/index.ts
  assets/img/size-guide.png
  components/mypage/MypageMain.tsx
  components/mysize/Mysize.tsx
  components/register/NextButton.tsx
  hooks/business/user.ts
  hooks/common/useRedirect.ts
  pages/login/index.tsx
  pages/register/index.tsx
  types/user/client.ts
  types/user/remote.ts
Labels: FEAT

#130 불필요한 코드 삭제, 최종 QA 반영
  .babelrc
  components/category/CategoryMain.tsx
  components/common/Header.tsx
  components/common/MenuBar.tsx
  components/common/SizeForm/SizeForm.tsx
  components/common/ThumbNail/ThumbNail.tsx
  components/common/modal/LottiePlayer.tsx
  components/home/AddCategoryModal.tsx
  components/home/HomeLanding.tsx
  components/mypage/MypageMain.tsx
  components/mysize/Mysize.tsx
  components/register/Register.tsx
  components/register/SizeOption.tsx
  components/welcome/ThirdPart.tsx
  hooks/common/index.ts
  hooks/common/useRedirect.ts
  hooks/queries/category.ts
  hooks/queries/mySize.ts
  hooks/queries/mypageHistory.ts
  hooks/ui/index.ts
  next.config.js
  package-lock.json
  package.json
  pages/_document.tsx
  pages/category/index.tsx
  pages/home/index.tsx
  pages/landing/index.tsx
  pages/login/index.tsx
  pages/mypage/index.tsx
  pages/mysize/index.tsx
  pages/register/index.tsx
  styles/GlobalStyle.tsx
  styles/theme.ts
Labels: FIX, FEAT

#140 리다이렉트 수정
  components/common/AsyncBoundary.tsx
  components/common/SizeForm/SizeForm.tsx
  components/register/Register.tsx
Labels: FIX
