Repository OWN-SIZE/onsize-website, pull requests merged in 2023-01, with the labels that each got.

#5 글로벌 스타일 적용 및 로그인 뷰 구현
  .babelrc
  assets/img/asset.tsx
  assets/img/google-login.png
  package-lock.json
  package.json
  pages/_app.tsx
  pages/login/index.tsx
  styles/GlobalStyle.tsx
  styles/globals.css
  tsconfig.json
Labels: Feat

#6 공통 컴포넌트 - 헤더, 메뉴바 구현
  components/common/Header.tsx
  components/common/Layout.tsx
  components/common/MenuBar.tsx
  pages/_app.tsx
  pages/home/index.tsx
Labels: Common

#12 Feat/#8 마이페이지- 히스토리뷰
  assets/icon/profileDefault.svg
  pages/mypage/index.tsx
  styles/theme.ts
  svg.d.ts
Labels: Feat

#11 랜딩페이지 및 로그인 뷰 구현
  assets/img/chrome-webstore.png
  assets/img/index.ts
  hooks/queries/user.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/landing/index.tsx
  pages/login/index.tsx
  states/user.ts
Labels: FEAT

#20 회원가입 사이즈 입력 폼 뷰 구현
  assets/icon/index.ts
  assets/icon/radio-clicked.png
  assets/icon/radio.png
  assets/img/bottom.png
  assets/img/index.ts
  assets/img/top-bottom.png
  assets/img/top.png
  components/common/SizeForm/SizeForm.tsx
  components/register/NextButton.tsx
  components/register/Progress.tsx
  components/register/SizeOption.tsx
  package-lock.json
  package.json
  pages/_document.tsx
  pages/register/index.tsx
  styles/theme.ts
Labels: COMMON, FEAT

#19 Feat/#17 마이페이지 히스토리 뷰 - 히스토리 모달
  assets/icon/link.png
  components/common/Header.tsx
  pages/mypage/historyModal.tsx
  pages/mypage/index.tsx
  styles/theme.ts
Labels: FEAT

#21 Feat/#18 공통 모달 템플릿 및 탈퇴 모달 구현
  components/common/Modal.tsx
  pages/mypage/index.tsx
  pages/register/index.tsx
  styles/theme.ts
Labels: COMMON, FEAT

#26 [회원가입] 사이즈 유효성 검사 Alert 구현
  components/common/SizeForm/Alert.tsx
  components/common/SizeForm/SizeForm.tsx
  components/common/modal/ModalPortal.ts
  components/register/NextButton.tsx
  components/register/SizeOption.tsx
  pages/_document.tsx
  pages/register/index.tsx
  styles/GlobalStyle.tsx
Labels: COMMON, FEAT

#15 home_처음, home_메인, thumbnail 공통 컴포넌트화
  assets/icon/addCategoryIcon.png
  assets/icon/closetIcon.png
  assets/icon/delete.png
  assets/icon/edit.png
  assets/icon/hover_delete.png
  assets/icon/hover_edit.png
  assets/icon/hover_pin.png
  assets/icon/hover_pin_fill.png
  assets/icon/index.ts
  assets/icon/pin.png
  assets/icon/pin_button.png
  assets/icon/pin_button_fill.png
  assets/icon/recommended.png
  assets/icon/size.png
  components/common/MenuBar.tsx
  components/common/Modal.tsx
  components/common/ThumbNail/ThumbNail.tsx
  components/home/HomeFirst.tsx
  components/home/HomeLanding.tsx
  components/home/HomeMain.tsx
  components/home/Product.tsx
  pages/_document.tsx
  pages/home/index.tsx
  pages/mypage/historyModal.tsx
  pages/mypage/index.tsx
  styles/theme.ts
  svg.d.ts
  types/common.ts
Labels: FEAT, Home

#47 로그인 api 통신 및 localStorage 갱신
  apis/user.ts
  hooks/business/mySize.ts
  hooks/business/user.ts
  hooks/queries/user.ts
  pages/login/index.tsx
  pages/register/index.tsx
  states/user.ts
  types/user/client.ts
  types/user/remote.ts
Labels: FEAT

#52 튜토리얼 모달 구현 및 로티 삽입
  assets/icon/arrow-left.png
  assets/icon/arrow-right.png
  assets/icon/index.ts
  assets/lottie/tutorial01.json
  assets/lottie/tutorial02.json
  assets/lottie/tutorial03.json
  assets/lottie/tutorial04.json
  components/common/Modal.tsx
  components/common/modal/LottieModal.tsx
  components/home/HomeFirst.tsx
  package-lock.json
  package.json
  styles/theme.ts
Labels: FEAT

#51 feat/#37: 에러 페이지 생성
  assets/img/hanger.png
  assets/img/index.ts
  components/common/AsyncBoundary.tsx
  components/common/Error.tsx
  next.config.js
  pages/_app.tsx
  pages/login/index.tsx
  tsconfig.json
Labels: FEAT

#65 feat/#64: favIcon 및 title 등록
  pages/_app.tsx
  pages/_document.tsx
  public/favicon.ico
Labels: FEAT
